### PR TITLE
Drupal 9

### PR DESCRIPTION
**Pull request by AronNovak**
#26 

## Status
added the version to be included in the tests

### CODE REVIEW

**Comment by AronNovak** [comment]
@amitaibu At least the tests do pass under Drupal 9 too, likely the actual compatibility is also quite close.

**Comment by grasmash** [comment]
Any reason not to merge this?

**Comment by amitaibu** [comment]
@AronNovak ^^ ?

+ Hi @grasmash  :smile_cat:

**Comment by AronNovak** [comment]
@grasmash @amitaibu The only reason that I never tested it on a Drupal 9 site by myself, but we may simply trust the tests and see what happens.

**Comment by amitaibu** [comment]
@grasmash have you tried it on D9?

**Comment by amitaibu** [comment]
Thanks folks

**Pull request merged**
