### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@AronNovak can you please have a look at the failing test? It keeps failing - https://travis-ci.com/github/Gizra/logs_http/jobs/407273564

image

**Comment by AronNovak** [comment]
@amitaibu PHP 7.2 is not compatible with the new Composer 2.x.
We have two choices, either we downgrade composer (just pushed it), or alternatively we drop PHP 7.2 from Travis entirely, it would solve the problem too.

**Comment by amitaibu** [comment]
Thanks. Lets drop 7.2

**Comment by AronNovak** [comment]
https://git.drupalcode.org/project/coder.git/ returns 503 right now, I guess the PR will be green tomorrow if we restart the job in the morning.

**Comment by amitaibu** [comment]
Thanks

**Pull request merged**
