### PR TITLE
Fix UUID config key

### PR DESCRIPTION
**Pull request by berramou**

### CODE REVIEW

**Comment by AronNovak** [comment]
It seems to be a duplicate of https://github.com/Gizra/logs_http/pull/29/files , let me know if it's not the case.

**Comment by berramou** [comment]
@AronNovak  it's not duplicate but it's caused by https://github.com/Gizra/logs_http/pull/29 the uuid renamed in all places besides in _**defaultKeys**_

**Review by AronNovak — APPROVED** [review]

**Comment by AronNovak** [comment]
Thanks for spotting this then!

**Comment by berramou** [comment]
Thank you @AronNovak 
any plans for new stable release with D9 compatibility and those fixes !

**Comment by AronNovak** [comment]
@amitaibu I do not have access for that. Shall we sync d.o repo to GH and `tag` what we have?

**Comment by amitaibu** [comment]
@AronNovak I've granted you access also on d.o. - if you can please create a release there

**Pull request merged**
